version: '3.1'
services:
  mojaBazaSpremnik:
    image: mojabazaspremnik:v1
    container_name: 'mojaBazaSpremnik'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mojalozinka
    ports:
      - "5435:5432"