version: '3.1'
services:
  frontend:
    image: 'dm52390/or:frontend_v1.2'
    ports:
      - "80:80"
  backend:
    image: 'dm52390/or:backend_v1.3'
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - PORT=8080
      - PG_HOST=PostgreSQL
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=mojalozinka
      - PG_DATABASE=ORbaza
  PostgreSQL:
    image: 'dm52390/or:baza_v1'
    container_name: mojaBazaSpremnik
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mojalozinka
      - POSTGRES_USER=postgres
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
